backend:
  name: git-gateway
  branch: master

media_folder: 'public/images'
public_folder: '/images'

format: 'frontmatter'

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/pages/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'text' }
      - { label: 'Data', name: 'pubDate', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
